#!/bin/bash

set -eo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Build protobuf
protoc --proto_path="$DIR" --elixir_out=plugins=grpc:"$DIR" "$DIR/example.proto"

# Move to support folder
mv "$DIR/example.pb.ex" "$DIR/../support/example.pb.ex"
